/**
 * auth.js 同步脚本
 * 将 common-lib/auth.js 作为唯一源，自动分发到所有云函数
 * 用法：node sync-auth.js
 */
var fs = require('fs');
var path = require('path');

var root = __dirname;
var source = path.join(root, 'cloudfunctions/common-lib/auth.js');
var utilSource = path.join(root, 'cloudfunctions/common-lib/util.js');
var errorsSource = path.join(root, 'cloudfunctions/common-lib/errors.js');

// 需要同步 auth.js 的云函数
var targets = [
  'addRecord',
  'borrowManage',
  'cmdHandler',
  'contactManage',
  'goodsManage',
  'queryData',
  'saleManage',
  'submitSale',
  'transferManage',
  'userManage',
];

// 需要同步 util.js 的云函数
var utilTargets = ['cmdHandler', 'addRecord'];

if (!fs.existsSync(source)) {
  console.error('源文件不存在:', source);
  process.exit(1);
}

var header = '// AUTO-GENERATED by sync-auth.js — 请勿手改\n// 源文件: cloudfunctions/common-lib/auth.js\n\n';

targets.forEach(function (name) {
  var dir = path.join(root, 'cloudfunctions', name);
  if (!fs.existsSync(dir)) return;

  var content = header + fs.readFileSync(source, 'utf8').replace(header, '');
  var dest = path.join(dir, 'auth.js');
  var oldContent = '';
  try { oldContent = fs.readFileSync(dest, 'utf8'); } catch (e) {}

  if (oldContent.replace(header, '') !== content.replace(header, '')) {
    fs.writeFileSync(dest, content, 'utf8');
    console.log('✅ ' + name + '/auth.js');
  } else {
    console.log('   ' + name + '/auth.js (未变化)');
  }
});

// 同步 util.js 到需要的云函数
if (fs.existsSync(utilSource)) {
  var utilHeader = '// AUTO-GENERATED by sync-auth.js\n// 源文件: cloudfunctions/common-lib/util.js\n\n';
  utilTargets.forEach(function (name) {
    var dir = path.join(root, 'cloudfunctions', name);
    if (!fs.existsSync(dir)) return;

    var content = utilHeader + fs.readFileSync(utilSource, 'utf8').replace(utilHeader, '');
    var dest = path.join(dir, 'util.js');
    fs.writeFileSync(dest, content, 'utf8');
    console.log('✅ ' + name + '/util.js');
  });
}

// 同步 errors.js 到需要的云函数
if (fs.existsSync(errorsSource)) {
  var errorsHeader = '// AUTO-GENERATED by sync-auth.js\n// 源文件: cloudfunctions/common-lib/errors.js\n\n';
  targets.forEach(function (name) {
    var dir = path.join(root, 'cloudfunctions', name);
    if (!fs.existsSync(dir)) return;

    var content = errorsHeader + fs.readFileSync(errorsSource, 'utf8').replace(errorsHeader, '');
    var dest = path.join(dir, 'errors.js');
    var oldContent = '';
    try { oldContent = fs.readFileSync(dest, 'utf8'); } catch (e) {}

    if (oldContent.replace(errorsHeader, '') !== content.replace(errorsHeader, '')) {
      fs.writeFileSync(dest, content, 'utf8');
      console.log('✅ ' + name + '/errors.js');
    } else {
      console.log('   ' + name + '/errors.js (未变化)');
    }
  });
}

console.log('\n同步完成。下次部署前运行 node sync-auth.js 即可。');
